export const products = [
  // Cakes
  {
    id: 1,
    name: 'Signature Chocolate Truffle Cake',
    category: 'Cakes',
    originalPrice: 1800,
    price: 1500,
    discount: 17,
    rating: 4.9,
    reviews: 365,
    image: `${process.env.PUBLIC_URL}/Signature-Chocolate-Truffle-Cake.jpg`,
    shortDescription: 'Decadent chocolate sponge layered with silky dark truffle ganache.',
    fullDescription: 'Our Signature Chocolate Truffle Cake is made with three layers of moist Belgian chocolate sponge, filled and coated with a rich chocolate ganache. Finished with chocolate curls and gold dust, it is the ultimate celebration centerpiece.',
    features: ['Belgian chocolate ganache', 'Freshly baked to order', 'Hand-decorated finish', 'Egg-based sponge', 'Contains nuts', '12-14 servings'],
    specifications: { 'Weight': '1.5 kg', 'Serves': '12-14 slices', 'Storage': 'Refrigerated', 'Shelf Life': '48 hours' }
  },
  {
    id: 2,
    name: 'Velvet Berry Celebration Cake',
    category: 'Cakes',
    originalPrice: 2000,
    price: 1650,
    discount: 18,
    rating: 4.8,
    reviews: 298,
    image: `${process.env.PUBLIC_URL}/red-violute.png`,
    shortDescription: 'Classic red velvet cake layered with cream cheese frosting and fresh berries.',
    fullDescription: 'The Velvet Berry Celebration Cake combines luscious red velvet sponge with tangy cream cheese frosting and seasonal berries. Perfect for birthdays, anniversaries, or any special occasion.',
    features: ['Red velvet sponge', 'Premium cream cheese frosting', 'Fresh berry topping', 'Natural food colors', 'Eggless option available', '12 servings'],
    specifications: { 'Weight': '1.4 kg', 'Serves': '12 slices', 'Storage': 'Refrigerated', 'Shelf Life': '36 hours' }
  },

  // Pastries
  {
    id: 3,
    name: 'All-Butter French Croissant',
    category: 'Pastries',
    originalPrice: 320,
    price: 260,
    discount: 19,
    rating: 4.9,
    reviews: 412,
    image: `${process.env.PUBLIC_URL}/All-Butter-French-Croissant.jpg`,
    shortDescription: 'Golden, flaky croissant made with imported French butter.',
    fullDescription: 'Our croissants are handcrafted over 48 hours using laminated dough and cultured French butter. They bake up with a beautiful honeycomb crumb and crisp exterior.',
    features: ['Cultured French butter', '48-hour lamination', 'Hand-rolled layers', 'No preservatives', 'Fresh daily', 'Vegetarian'],
    specifications: { 'Quantity': '2 pieces', 'Serving': 'Ready to eat', 'Allergens': 'Gluten, Dairy', 'Shelf Life': '24 hours' }
  },
  {
    id: 4,
    name: 'Almond Pain au Chocolat',
    category: 'Pastries',
    originalPrice: 360,
    price: 295,
    discount: 18,
    rating: 4.7,
    reviews: 254,
    image: `${process.env.PUBLIC_URL}/Almond-Pain-au-Chocolat.jpg`,
    shortDescription: 'Layered pastry filled with dark chocolate and topped with almond frangipane.',
    fullDescription: 'This indulgent pastry features a buttery laminated dough filled with couverture chocolate, finished with almond frangipane and toasted flakes for a satisfying crunch.',
    features: ['70% dark chocolate', 'Almond frangipane topping', 'Hand-laminated dough', 'Slow proofed overnight', 'Baked fresh daily', 'Vegetarian'],
    specifications: { 'Quantity': '2 pieces', 'Serving': 'Warm for best taste', 'Allergens': 'Gluten, Dairy, Nuts', 'Shelf Life': '24 hours' }
  },

  // Bread
  {
    id: 5,
    name: 'Artisan Sourdough Loaf',
    category: 'Bread',
    originalPrice: 380,
    price: 320,
    discount: 16,
    rating: 4.9,
    reviews: 310,
    image: `${process.env.PUBLIC_URL}/Artisan-Sourdough-Loaf.jpg`,
    shortDescription: 'Slow-fermented sourdough with a caramelized crust and airy crumb.',
    fullDescription: 'Crafted with a wild yeast starter and stone-ground flour, our sourdough loaf is fermented for 20 hours for exceptional flavor and digestibility.',
    features: ['Natural wild starter', 'Stone-ground flours', 'Slow fermentation', 'No commercial yeast', 'Hand-scored crust', 'Vegan'],
    specifications: { 'Weight': '750 g', 'Shelf Life': '72 hours', 'Storage': 'Room temperature', 'Serving': 'Slice and toast' }
  },
  {
    id: 6,
    name: 'Multigrain Wellness Bread',
    category: 'Bread',
    originalPrice: 360,
    price: 290,
    discount: 19,
    rating: 4.8,
    reviews: 228,
    image: `${process.env.PUBLIC_URL}/Multigrain-Wellness-Bread.jpg`,
    shortDescription: 'Wholesome loaf packed with seven grains, seeds, and natural honey.',
    fullDescription: 'A nutritious loaf featuring whole wheat, oats, flax, pumpkin, and sunflower seeds lightly sweetened with forest honey. Ideal for sandwiches and breakfast toast.',
    features: ['Seven-grain blend', 'High fiber', 'No refined sugar', 'Cold-pressed oil', 'No preservatives', 'Vegan-friendly'],
    specifications: { 'Weight': '650 g', 'Shelf Life': '72 hours', 'Storage': 'Airtight container', 'Serving': 'Slice to preferred thickness' }
  },

  // Cookies
  {
    id: 7,
    name: 'Belgian Chocolate Chunk Cookies',
    category: 'Cookies',
    originalPrice: 450,
    price: 360,
    discount: 20,
    rating: 4.9,
    reviews: 540,
    image: `${process.env.PUBLIC_URL}/Belgian-Chocolate-Chunk-Cookies.jpg`,
    shortDescription: 'Soft and chewy cookies loaded with Belgian chocolate chunks.',
    fullDescription: 'Our best-selling cookie features browned butter, muscovado sugar, and generous chunks of Belgian couverture for a gooey center and crispy edges.',
    features: ['Browned butter base', '70% chocolate chunks', 'Sea salt flakes', 'Hand-rolled dough', 'No preservatives', 'Bakes to order'],
    specifications: { 'Quantity': '6 cookies', 'Storage': 'Airtight jar', 'Shelf Life': '5 days', 'Allergens': 'Gluten, Dairy' }
  },
  {
    id: 8,
    name: 'Pistachio Cranberry Shortbread',
    category: 'Cookies',
    originalPrice: 420,
    price: 340,
    discount: 19,
    rating: 4.7,
    reviews: 268,
    image: `${process.env.PUBLIC_URL}/Pistachio-Cranberry-Shortbread.png`,
    shortDescription: 'Buttery shortbread infused with pistachios and tart cranberries.',
    fullDescription: 'Delicate melt-in-your-mouth shortbread made with cultured butter, toasted pistachios, and cranberries. Perfect with tea or as a gift box.',
    features: ['Cultured butter', 'Hand-chopped nuts', 'No artificial colors', 'Gift-ready packaging', 'Small batch baked', 'Vegetarian'],
    specifications: { 'Quantity': '12 pieces', 'Shelf Life': '10 days', 'Storage': 'Cool, dry place', 'Allergens': 'Gluten, Nuts, Dairy' }
  },

  // Cupcakes
  {
    id: 9,
    name: 'Rainbow Celebration Cupcakes',
    category: 'Cupcakes',
    originalPrice: 520,
    price: 420,
    discount: 19,
    rating: 4.8,
    reviews: 345,
    image: `${process.env.PUBLIC_URL}/Rainbow-Celebration-Cupcakes.png`,
    shortDescription: 'Vanilla cupcakes topped with rainbow buttercream swirls and sprinkles.',
    fullDescription: 'Soft vanilla sponge baked in colorful liners, finished with buttercream swirls in rainbow hues and crunchy confetti sprinkles. Kid-approved party favorite.',
    features: ['Madagascar vanilla', 'Swiss meringue buttercream', 'Hand-piped swirls', 'Festive sprinkles', 'Eggless option available', 'Perfect for parties'],
    specifications: { 'Quantity': '6 cupcakes', 'Storage': 'Refrigerated', 'Shelf Life': '48 hours', 'Serving': 'Bring to room temperature before serving' }
  },
  {
    id: 10,
    name: 'Salted Caramel Crunch Cupcakes',
    category: 'Cupcakes',
    originalPrice: 540,
    price: 440,
    discount: 19,
    rating: 4.9,
    reviews: 278,
    image: `${process.env.PUBLIC_URL}/Salted-Caramel-Crunch-Cupcakes.jpg`,
    shortDescription: 'Chocolate cupcakes filled with caramel and topped with praline crunch.',
    fullDescription: 'Indulgent chocolate sponge filled with homemade salted caramel, frosted with caramel buttercream, and sprinkled with almond praline crunch.',
    features: ['Salted caramel core', 'Dark cocoa sponge', 'Buttercream frosting', 'Almond praline topping', 'Premium ingredients', 'Freshly baked'],
    specifications: { 'Quantity': '6 cupcakes', 'Storage': 'Refrigerated', 'Shelf Life': '48 hours', 'Allergens': 'Gluten, Dairy, Nuts' }
  },

  // Toast
  {
    id: 11,
    name: 'Garlic Herb Toast Bites',
    category: 'Toast',
    originalPrice: 260,
    price: 210,
    discount: 19,
    rating: 4.6,
    reviews: 198,
    image: `${process.env.PUBLIC_URL}/Garlic-Herb-Toast-Bites.png`,
    shortDescription: 'Crispy toast rounds brushed with garlic butter and fresh herbs.',
    fullDescription: 'Perfect for soups and salads, these twice-baked toast bites are made from sourdough slices, brushed with garlic parsley butter, and baked till crunchy.',
    features: ['Hand-sliced sourdough', 'Garlic herb butter', 'Twice baked crunch', 'No preservatives', 'Ready-to-serve snack', 'Vegetarian'],
    specifications: { 'Quantity': '150 g pack', 'Shelf Life': '15 days', 'Storage': 'Airtight container', 'Serving': 'Serve straight from pack' }
  },
  {
    id: 12,
    name: 'Cinnamon Sugar Breakfast Toast',
    category: 'Toast',
    originalPrice: 240,
    price: 195,
    discount: 19,
    rating: 4.7,
    reviews: 156,
    image: `${process.env.PUBLIC_URL}/Cinnamon-Sugar-Breakfast-Toast.jpg`,
    shortDescription: 'Sweet toast slices dusted with cinnamon sugar and baked crisp.',
    fullDescription: 'A nostalgic breakfast treat made with milk bread slices brushed with butter, dusted with cinnamon sugar, and baked to a caramelized crunch.',
    features: ['Milk bread base', 'Cinnamon sugar topping', 'No artificial flavors', 'Kid-friendly snack', 'Ready-to-eat', 'Vegetarian'],
    specifications: { 'Quantity': '120 g pack', 'Shelf Life': '12 days', 'Storage': 'Cool, dry place', 'Serving': 'Enjoy straight from pack' }
  },

  // Sandwich
  {
    id: 13,
    name: 'Gourmet Veggie Club Sandwich',
    category: 'Sandwich',
    originalPrice: 420,
    price: 340,
    discount: 19,
    rating: 4.8,
    reviews: 220,
    image: `${process.env.PUBLIC_URL}/Gourmet-Veggie-Club-Sandwich.jpg`,
    shortDescription: 'Triple-decker sandwich layered with grilled veggies, pesto, and cheese.',
    fullDescription: 'A hearty sandwich featuring grilled zucchini, peppers, basil pesto, and smoked cheese layered between toasted multigrain bread with herbed mayo.',
    features: ['Fresh grilled vegetables', 'Homemade pesto spread', 'Smoked cheese slices', 'Multigrain bread', 'Served with chips', 'Vegetarian'],
    specifications: { 'Weight': '280 g', 'Serving': 'Ready to eat', 'Storage': 'Chilled', 'Shelf Life': '12 hours' }
  },
  {
    id: 14,
    name: 'Smoked Chicken Focaccia Sandwich',
    category: 'Sandwich',
    originalPrice: 460,
    price: 375,
    discount: 18,
    rating: 4.7,
    reviews: 176,
    image: `${process.env.PUBLIC_URL}/Smoked-Chicken-Focaccia-Sandwich.jpg`,
    shortDescription: 'Warm focaccia stuffed with smoked chicken, caramelized onions, and cheese.',
    fullDescription: 'This savoury sandwich combines herb focaccia with smoked chicken strips, caramelized onions, aged cheddar, and roasted garlic aioli.',
    features: ['House-baked focaccia', 'Smoked chicken filling', 'Aged cheddar cheese', 'Caramelized onions', 'Roasted garlic aioli', 'Served warm'],
    specifications: { 'Weight': '300 g', 'Serving': 'Heat before serving', 'Storage': 'Refrigerated', 'Shelf Life': '18 hours' }
  },

  // Bisckets
  {
    id: 15,
    name: 'Tea-Time Butter Bisckets',
    category: 'Bisckets',
    originalPrice: 320,
    price: 255,
    discount: 20,
    rating: 4.8,
    reviews: 304,
    image: `${process.env.PUBLIC_URL}/Tea-Time-Butter-Bisckets.png`,
    shortDescription: 'Classic butter bisckets with a tender crumb and golden glaze.',
    fullDescription: 'Enjoy with your evening chai, these melt-in-the-mouth butter bisckets are crafted with fresh creamery butter and a hint of Madagascan vanilla.',
    features: ['Creamery butter', 'Hand-cut shapes', 'No artificial additives', 'Traditional recipe', 'Light vanilla aroma', 'Vegetarian'],
    specifications: { 'Quantity': '200 g box', 'Shelf Life': '20 days', 'Storage': 'Airtight tin', 'Allergens': 'Gluten, Dairy' }
  },
  {
    id: 16,
    name: 'Jeera Masala Bisckets',
    category: 'Bisckets',
    originalPrice: 300,
    price: 240,
    discount: 20,
    rating: 4.6,
    reviews: 198,
    image: `${process.env.PUBLIC_URL}/Jeera-Masala-Bisckets.png`,
    shortDescription: 'Savory cumin-spiced bisckets baked crisp for tea-time snacking.',
    fullDescription: 'A nostalgic savory treat featuring roasted cumin seeds, ajwain, and pepper balanced in a buttery biscuit dough baked to perfection.',
    features: ['Roasted cumin flavor', 'Balanced savory spices', 'Crispy texture', 'No preservatives', 'Perfect with tea', 'Vegetarian'],
    specifications: { 'Quantity': '200 g box', 'Shelf Life': '25 days', 'Storage': 'Cool, dry place', 'Allergens': 'Gluten, Dairy' }
  },

  // Namkeens
  {
    id: 17,
    name: 'Royal Kaju Mixture',
    category: 'Namkeens',
    originalPrice: 420,
    price: 345,
    discount: 18,
    rating: 4.9,
    reviews: 268,
    image: `${process.env.PUBLIC_URL}/Royal-Kaju-Mixture.png`,
    shortDescription: 'Premium namkeen blend with roasted cashews, sev, and spice dusting.',
    fullDescription: 'A luxurious namkeen featuring whole roasted cashews, crunchy sev, flattened rice, and a signature spice blend with curry leaves and saffron.',
    features: ['Whole roasted cashews', 'Signature spice mix', 'Slow-roasted ingredients', 'No artificial colors', 'Small batch crafted', 'Vegetarian'],
    specifications: { 'Quantity': '250 g pack', 'Shelf Life': '45 days', 'Storage': 'Airtight jar', 'Spice Level': 'Medium' }
  },
  {
    id: 18,
    name: 'Spicy Murukku Twists',
    category: 'Namkeens',
    originalPrice: 360,
    price: 290,
    discount: 19,
    rating: 4.7,
    reviews: 210,
    image: `${process.env.PUBLIC_URL}/Spicy-Murukku-Twists.png`,
    shortDescription: 'Crispy rice flour spirals seasoned with pepper, sesame, and curry leaves.',
    fullDescription: 'Traditional South Indian murukku handcrafted using stone-ground rice flour and roasted gram flour. Seasoned with pepper, sesame seeds, and curry leaves.',
    features: ['Stone-ground flours', 'Hand-extruded spirals', 'Cold-pressed sesame oil', 'No preservatives', 'Gluten-free', 'Vegan'],
    specifications: { 'Quantity': '220 g pack', 'Shelf Life': '40 days', 'Storage': 'Airtight container', 'Spice Level': 'Medium-high' }
  },

  // Softdrinks
  {
    id: 19,
    name: 'Cold Brew Coffee Bottle',
    category: 'Softdrinks',
    originalPrice: 260,
    price: 210,
    discount: 19,
    rating: 4.8,
    reviews: 186,
    image: `${process.env.PUBLIC_URL}/Cold-Brew-Coffee-Bottle.png`,
    shortDescription: 'Slow-steeped cold brew made with single-origin Arabica beans.',
    fullDescription: 'Refreshing cold brew steeped for 16 hours, offering smooth chocolate notes with low acidity. Served in a grab-and-go glass bottle.',
    features: ['Single-origin beans', '16-hour steep', 'No added sugar', 'Glass bottle packaging', 'Serve chilled', 'Vegan'],
    specifications: { 'Volume': '300 ml', 'Shelf Life': '7 days', 'Storage': 'Refrigerated', 'Caffeine': '180 mg per bottle' }
  },
  {
    id: 20,
    name: 'Fresh Pressed Orange Cooler',
    category: 'Softdrinks',
    originalPrice: 240,
    price: 195,
    discount: 19,
    rating: 4.7,
    reviews: 162,
    image: `${process.env.PUBLIC_URL}/Fresh-Pressed-Orange-Cooler.png`,
    shortDescription: 'Cold-pressed Valencia oranges blended with mint and honey.',
    fullDescription: 'A bright and refreshing cooler combining cold-pressed orange juice, a hint of mint, and natural honey. No concentrates or preservatives.',
    features: ['Cold-pressed juice', 'Natural sweeteners', 'No preservatives', 'High vitamin C', 'Serve chilled', 'Vegetarian'],
    specifications: { 'Volume': '350 ml', 'Shelf Life': '5 days', 'Storage': 'Refrigerated', 'Sweetener': 'Honey' }
  },

  // Extra More
  {
    id: 21,
    name: 'Homemade Berry Preserve',
    category: 'Extra More',
    originalPrice: 380,
    price: 320,
    discount: 16,
    rating: 4.9,
    reviews: 214,
    image: `${process.env.PUBLIC_URL}/Homemade-Berry-Preserve.png`,
    shortDescription: 'Small-batch preserve made with strawberries, blueberries, and lemon zest.',
    fullDescription: 'Slow-simmered berries with organic cane sugar and fresh lemon zest create a vibrant spread that pairs with toast, scones, or yogurt bowls.',
    features: ['Mixed berry blend', 'No artificial pectin', 'Handcrafted in small batches', 'Glass jar packaging', 'No preservatives', 'Vegetarian'],
    specifications: { 'Weight': '250 g jar', 'Shelf Life': '45 days', 'Storage': 'Refrigerated after opening', 'Sweetness': 'Medium' }
  },
  {
    id: 22,
    name: 'Classic Peanut Butter Spread',
    category: 'Extra More',
    originalPrice: 440,
    price: 270,
    discount: 21,
    rating: 4.8,
    reviews: 240,
    image: `${process.env.PUBLIC_URL}/Classic-Peanut-Butter-Spread.png`,
    shortDescription: 'Creamy peanut butter made with slow-roasted peanuts and sea salt.',
    fullDescription: 'Our peanut butter is freshly stone-ground from slow-roasted peanuts with just a touch of sea salt. No hydrogenated oils or refined sugar.',
    features: ['Stone-ground texture', 'Slow-roasted peanuts', 'No refined sugar', 'Protein rich', 'No preservatives', 'Vegan'],
    specifications: { 'Weight': '300 g jar', 'Shelf Life': '60 days', 'Storage': 'Room temperature', 'Ingredients': 'Peanuts, Sea Salt' }
  },
];